name: Build on Main Merge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull from main
        run: git pull origin main

      - name: Build
        run: |
          yarn
          yarn build
          
      - name: Copy files to temporary directory
        run: |
          mkdir temp_dir
          rsync -av --exclude-from=.gitignore . temp_dir/
          
      - name: Configure Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          
      - name: Create or checkout build branch
        run: |
          if git show-ref --verify --quiet refs/heads/build; then
            git checkout build
          else
            git checkout -b build
          fi
            
      - name: Push to build branch
        run: |
          git add -A
          git commit -m "Update build"
          git push origin build
          
      - name: Clean up
        run: |
          rm -rf temp_dir
